Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.provider "virtualbox" do |vb|
  vb.name = "VagrantVM2"
  vb.gui = false
  vb.memory = "4096"
  vb.cpus = 2
  end
  
  config.vm.hostname = "VagrantVM2"
  config.vm.synced_folder ".", "/home/vagrant/code",
  owner: "www-data", group: "www-data"
  
  #node_exporter
  config.vm.network "forwarded_port", guest: 9100, host: 33070
  #MySql_exporter
  config.vm.network "forwarded_port", guest: 9104, host: 33090

  config.vm.provision "file", source: "mysql_exporter.service", destination: "/tmp/mysql_exporter.service"
  config.vm.provision "file", source: "node_exporter.service", destination: "/tmp/node_exporter.service"


  config.vm.provision "shell", path: "installation.sh"
end
