global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["localhost:9093"]

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter_vm2"
    scrape_interval: 10s
    static_configs:
      - targets: ["46.219.127.6:33070"]
  
  - job_name: "mysql_exporter"
    static_configs:
      - targets: ["46.219.127.6:33090"]

  - job_name: 'alertmanager'
    static_configs:
    - targets: ['localhost:9093']
  
  - job_name: "node_exporter_vm1"
    static_configs:
      - targets: ["localhost:9100"]